export const propertyLayout = [{
    id: 'wineType',
    label: '酒品类型',
    type: 'text'
}, {
    id: 'grapeType',
    label: '葡萄品种',
    type: 'text'
}, {
    id: 'year',
    label: '年份',
    type: 'text'
}, {
    id: 'degree',
    label: '酒精度',
    type: 'text'
}, {
    id: 'ml',
    label: '净含量',
    type: 'text'
}, {
    id: 'treeAge',
    label: '平均树龄',
    type: 'text'
}, {
    id: 'wineMaker',
    label: '酿酒师',
    type: 'text'
}, {
    id: 'merchantName',
    label: '酒庄',
    type: 'text'
}, {
    id: 'productArea',
    label: '产区',
    type: 'text'
}, {
    id: 'reason',
    label: '推荐理由',
    type: 'description'
}, {
    id: 'storyPic',
    label: '',
    type: 'images'
}];
