export const propertyLayout = [{
    id: 'wineType',
    label: '酒品类型',
    type: 'text'
}, {
    id: 'grapeType',
    label: '葡萄品种及介绍',
    type: 'btn-group-text'
}, {
    id: 'year',
    label: '年份',
    type: 'text'
}, {
    id: 'degree',
    label: '酒精度',
    type: 'text'
}, {
    id: 'ml',
    label: '净含量',
    type: 'text'
}, {
    id: 'treeAge',
    label: '平均树龄',
    type: 'text'
}, {
    id: 'wineMaker',
    label: '酿酒师及介绍',
    type: 'btn-group-text'
}, {
    id: 'merchantName',
    label: '酒庄',
    type: 'text'
}, {
    id: 'productArea',
    label: '产区',
    type: 'text'
}, {
    id: 'technology',
    label: '酿造工艺',
    type: 'text'
}, {
    id: 'barrel',
    label: '橡木桶',
    type: 'text'
}, {
    id: 'fillingTime',
    label: '罐装时间',
    type: 'text'
}, {
    id: 'expiryDate',
    label: '保质期',
    type: 'text'
}, {
    id: 'drinkTemperature',
    label: '适饮温度',
    type: 'text'
}, {
    id: 'soberTime',
    label: '醒酒时间',
    type: 'text'
}, {
    id: 'collocation',
    label: '搭配推荐',
    type: 'text'
}, {
    id: 'yield',
    label: '产量',
    type: 'text'
}, {
    id: 'inventory',
    label: '库存量',
    type: 'text'
}, {
    id: 'prizePics',
    label: '获奖照片',
    type: 'btn-group-img'
}, {
    id: 'inspectionReportPics',
    label: '检验报告',
    type: 'btn-group-img'
}];
