server:
  context-path: /wine
  port: 7080

spring:
  datasource:
      url: jdbc:mysql://123.57.234.184:3309/wine?characterEncoding=utf8
      username: wine
      password: wangsong123
      driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  jpa:
    show-sql: true
  http:
    multipart:
      enabled: true # Enable support of multi-part uploads.
      file-size-threshold: 0 # Threshold after which files will be written to disk. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
      location: /opt/fdp/upload/ #/Users/sxjiang/Documents/ # Intermediate location of uploaded files.
      #location: /Users/sxjiang/Documents/wine #/Users/sxjiang/Documents/ # Intermediate location of uploaded files.
      max-file-size: 30MB # Max file size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
      max-request-size: 35MB # Max request size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size
      resolve-lazily: false

  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    request-context-attribute: rc
    settings:
      auto_import: common/datatable.ftl as dt,common/spring.ftl as spring
wine:
  picPath: http://123.57.234.184/wineStatic/images/  #图片访问路径
  storePath: /data/wine/static/
  #storePath: /Users/sxjiang/Documents/wine/
